### ISSUE TITLE
MathJax becomes slow after clicking on a lot of surfaces

### ISSUE THREAD

**Issue by jcommelin** [superficie/superficie-algebriche#19]
Might there be some internal buffer that isn't emptied? Here MathJax starts to render very slowly after clicking on say 30 surfaces. It might help to change the Kodaira dimension a couple of times, and enable/disable analytic surfaces.

**Comment by pbelmans** [comment]
I was also experiencing some lag in Firefox. I'll look into it in the weekend, now it's time for more serious business.

**Comment by pbelmans** [comment]
It's 2019. Computers are quicker now. Except yours.
